In [1]:
import numpy as np

In [2]:
X = np.array([1,2])
X.shape

(2,)

In [3]:
W = np.array([[1,3,5],[2,4,6]])
W

array([[1, 3, 5],
       [2, 4, 6]])

In [4]:
W.shape

(2, 3)

In [6]:
Y = np.dot(X,W)
Y

array([ 5, 11, 17])

In [8]:
X = np.array([1.0,0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2,0.4,0.6]])
B1 = np.array([0.1, 0.2, 0.3])

W1.shape

(2, 3)

In [9]:
X.shape

(2,)

In [10]:
B1.shape

(3,)

In [12]:
A1 = np.dot(X, W1)+B1
A1.shape

(3,)

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1)
A1

array([0.3, 0.7, 1.1])

In [14]:
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [15]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1, 0.2])
Z1.shape

(3,)

In [16]:
W2.shape

(3, 2)

In [17]:
B2.shape

(2,)

In [18]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [26]:
def identity_function(x):
    return x

W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(A2, W3) + B3
Y = identity_function(A3)
Y

array([0.39442138, 0.84045873])

In [28]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1)+b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1,W2) +b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3) +b3
    y = identity_function(a3)
    return y

network = init_network()
x = np.array([1.0,0.5])
y = forward(network, x)
y

array([0.31682708, 0.69627909])

In [30]:
a = np.array([0.3,2.9,4.0])

exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [31]:
sum_exp_a = np.sum(exp_a)
sum_exp_a

74.1221542101633

In [32]:
y = exp_a / sum_exp_a
y

array([0.01821127, 0.24519181, 0.73659691])

In [36]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

a = np.array([1010,1000,990])
np.exp(a) / np.sum(np.exp(a))

C:\Users\yoonkyu\AppData\Local\Temp\ipykernel_52760\1657086680.py:9: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
C:\Users\yoonkyu\AppData\Local\Temp\ipykernel_52760\1657086680.py:9: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [34]:
c = np.max(a)
a-c

array([  0, -10, -20])

In [35]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [38]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
y

array([0.01821127, 0.24519181, 0.73659691])

In [39]:
np.sum(y)

1.0

In [40]:
np.exp2([2,4,6])

array([ 4., 16., 64.])