In [1]:
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [2]:
len(a)

5

In [3]:
a[0]

1

In [4]:
a[4]

5

In [5]:
a

[1, 2, 3, 4, 5]

In [6]:
a[4] = 99
a

[1, 2, 3, 4, 99]

In [7]:
a[0:2]

[1, 2]

In [8]:
a[1:]

[2, 3, 4, 99]

In [9]:
a[:3]

[1, 2, 3]

In [10]:
a[:-1]

[1, 2, 3, 4]

In [11]:
a[:-2]

[1, 2, 3]

In [12]:
a[-1]

99

In [13]:
a[-5]

1

In [14]:
me = {'height':180}

In [16]:
me['height']

180

In [17]:
me['weight'] = 70
me

{'height': 180, 'weight': 70}

In [18]:
hungry = True
sleepy = False

In [19]:
type(hungry)

bool

In [20]:
not hungry

False

In [21]:
hungry and sleepy

False

In [22]:
hungry or sleepy

True

In [23]:
if hungry:
    print("I'm hungry")

I'm hungry


In [24]:
hungry = False
if hungry:
    print("I'm happy")
else:
    print("I'm not hungry")
    print("I'm sleepy")

    

I'm not hungry
I'm sleepy


In [27]:
for i in [1,2,3]:
    print(i, sep=" ")

1
2
3


In [28]:
def hello():
    print("Hello World")

In [29]:
hello()

Hello World


In [36]:
def hello(object):
    print("Hello "+object+"!")

hello("cat")

Hello cat!


In [37]:
class Man:
    def __init__(self, name):
        self.name = name
        print('Initialized')

    def hello(self):
        print("Hello "+self.name + "!")

    def goodbye(self):
        print("Good-bye "+self.name + "!")

m = Man("David")



Initialized


In [38]:
m.hello()

Hello David!


In [39]:
m.goodbye()

Good-bye David!


In [40]:
import numpy as np
x= np.array([1.0, 2.0, 3.0])
x


array([1., 2., 3.])

In [41]:
type(x)

numpy.ndarray

In [42]:
y = np.array([2.0, 4.0, 6.0])
x+y

array([3., 6., 9.])

In [43]:
x-y

array([-1., -2., -3.])

In [44]:
x*y

array([ 2.,  8., 18.])

In [45]:
x/y

array([0.5, 0.5, 0.5])

In [46]:
x/2.0

array([0.5, 1. , 1.5])

In [47]:
type(x/2.0)

numpy.ndarray

In [48]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [49]:
type(A)

numpy.ndarray

In [50]:
A.shape

(2, 2)

In [51]:
A.dtype

dtype('int32')

In [52]:
B = np.array([[3, 0], [0,6]])
A+B

array([[ 4,  2],
       [ 3, 10]])

In [53]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [54]:
A/B

C:\Users\yoonkyu\AppData\Local\Temp\ipykernel_26968\713994841.py:1: RuntimeWarning: divide by zero encountered in divide
  A/B


array([[0.33333333,        inf],
       [       inf, 0.66666667]])

In [55]:
A

array([[1, 2],
       [3, 4]])

In [56]:
A*10

array([[10, 20],
       [30, 40]])

In [57]:
X = np.array([[51,55],[14,19], [0,4]])
X

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [58]:
X[0]

array([51, 55])

In [59]:
X[0][1]

55

In [60]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [62]:
for row in X:
    print(row[0])

51
14
0


In [63]:
X = X.flatten()
X

array([51, 55, 14, 19,  0,  4])

In [64]:
X[np.array([0,2,4])]

array([51, 14,  0])

In [65]:
X>15

array([ True,  True, False,  True, False, False])

In [66]:
X[X>15]

array([51, 55, 19])